### ISSUE TITLE
Add dataflow-runner configs

### ISSUE THREAD

**Issue by chuwy** [dilyand/spark-web-model#1]
Hey @dilyand!

My current plan is to mimic the snowplow-approach: namely create some tickets (per feature or fix) and then (probably tomorrow) make a PR with each of them separately implemented with description on why do we need this and why did we implement it that way. What do you think about this approach?

For example, we need this one (dataflow-runner configs) to avoid storing/passing AWS keys to application and to reduce manual labor during launching job.

**Comment by dilyand** [comment]
Sounds great @chuwy ! Looking forward to the PRs.
